---
#- name: Create Postgres db on RDS
#  local_action:
#    module: rds
#    command: create
#    instance_name: "{{ rds.rds_instance_name }}"
#    db_engine: "{{ rds.db_engine }}"
#    size: "{{ rds.size }}"
#    instance_type: "{{ rds.instance_type }}"
#    db_name: "{{ rds.db_name }}"
#    username: "{{ rds.username }}"
#    password: "{{ rds.password }}"
#    region: "{{ rds.region }}"
#    subnet: "{{ rds.subnet }}"
#    vpc_security_groups: "{{ rds.vpc_security_groups }}"
#    multi_zone: no
#    port: 5432
#    wait: yes
#    wait_timeout: 3600
#  register: rds
#
#- name: Get RDS instance facts
#  local_action:
#    module: rds
#    command: facts
#    instance_name: "{{ rds.rds_instance_name }}"
#    region: "{{ aws.region }}"
#  when: rds|succeeded

 - name: Set RDS parameters to environment variable
#  debug: msg= "RDS endpoint is --> {{ rds.instance.endpoint }}"
   #shell: echo DB_HOST is $DB_HOST
   shell: export DB_NAME="{{ rds.db_name }}"
#   shell: echo DB_USER is $DB_USER
#   shell: echo DB_PASS is $DB_PASS

   environment:
#    DB_HOST: "{{ rds.instance.endpoint }}"
     DB_NAME: "{{ rds.db_name }}"
#     DB_USER: "{{ rds.username }}"
#     DB_PASS: "{{ rds.password }}"
   register: shellout
   become: true
#  debug: var=shellout





