---
 - name: Get Java package
   s3:
    bucket: "{{aws.bucket}}"
    object: oracle-java8-jdk_8u144_amd64.deb
    dest: "{{ env.project_dir }}/"
    mode: get
    ignore_nonexistent_bucket: true

 - name: Get Samsara package
   s3:
    bucket: "{{aws.bucket}}"
    object: Samsara-1.3.5.RELEASE.jar
    dest: "{{ env.project_dir }}/"
    mode: get
    ignore_nonexistent_bucket: true

 - name: Get Liquibase package
   s3:
    bucket: "{{aws.bucket}}"
    object: liquibase-3.5.3-bin.tar.gz
    dest: "{{ env.liquibase_dir }}/"
    mode: get
    ignore_nonexistent_bucket: true

 - name: Get Postgresql jdbc driver
   s3:
    bucket: "{{aws.bucket}}"
    object: postgresql-42.1.4.jar
    dest: "{{ env.liquibase_dir }}/"
    mode: get
    ignore_nonexistent_bucket: true