---
# - name: Get Java package.
#   aws_s3:
#    bucket: "{{aws.bucket}}"
#    object: oracle-java8-jdk_8u144_amd64.deb
#    dest: "{{env.project_dir}}/oracle-java8-jdk_8u144_amd64.deb"
#    mode: get
#    retries: 5
#    overwrite: different

 - name: Get Samsara package.
   aws_s3:
    bucket: "{{aws.bucket}}"
    object: Samsara-1.3.5.RELEASE.jar
    dest: "{{ env.project_dir }}/Samsara-1.3.5.RELEASE.jar"
    mode: get
    retries: 5
    overwrite: different

 - name: Get Liquibase package.
   aws_s3:
    bucket: "{{aws.bucket}}"
    object: liquibase-3.5.3-bin.tar.gz
    dest: "{{ env.liquibase_dir }}/liquibase-3.5.3-bin.tar.gz"
    mode: get
    retries: 5
    overwrite: different

 - name: Get Postgresql jdbc driver.
   aws_s3:
    bucket: "{{aws.bucket}}"
    object: postgresql-42.1.4.jar
    dest: "{{ env.liquibase_dir }}/postgresql-42.1.4.jar"
    mode: get
    retries: 5
    overwrite: different