---
- name: Check if predefined Java package is installed.
  command: dpkg-query -l oracle-java8-jdk_8u144_amd64.deb
  register: dpkg_check
  ignore_errors: True

- name: Install Java package.
  command: dpkg -i {{env.project_dir}}/oracle-java8-jdk_8u144_amd64.deb
  when: dpkg_check.rc == 1
  register: java_state
  ignore_errors: True

- name: Install required packages for Java.
  command: apt-get -f install -y
  when: java_state.rc == 1
  register: java_state

- name: Install Java package again.
  command: dpkg -i {{env.project_dir}}/oracle-java8-jdk_8u144_amd64.deb
  when: dpkg_check.rc == 1
  register: java_inst_result

- name: Update Java alternatives.
  command: update-alternatives --set java /usr/lib/jvm/jdk-8-oracle-x64/jre/bin/java
  when: java_inst_result.rc == 0



