---
 - name: Start Java application.
   shell: "java -jar {{ env.project_dir }}/Samsara-1.3.5.RELEASE.jar > /dev/null 2&1 &"
   args:
     executable: /bin/bash
   register: app_state
   become: true

 - name: Wait for Java application to become available
   wait_for:
     port: 9000
     host: localhost
     delay: 60
     timeout: 200
   when: app_state|succeeded
   register: app_up

 - name: Check that you can connect (GET) to a page and it returns a status 200.
   uri:
     url: http://localhost:9000/login
   when: app_up|succeeded
