---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
#  environment:
#    DB_HOST: ""
#    DB_NAME: "{{ rds.db_name }}"
#    DB_USER: "{{ rds.username }}"
#    DB_PASS: "{{ rds.password }}"
  tasks:
    - include: tasks/awscli.yml
    - include: tasks/getfroms3.yml
    - include: tasks/javainstall.yml
    - include: tasks/create_rds_and_start_app.yml
#    - include: tasks/run_app.yml

