---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/awscli.yml
               tasks/javainstall.yml
               #tasks/create_rds.yml
               tasks/getfroms3.yml