---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    #- include: tasks/awscli.yml
    #- include: tasks/javainstall.yml
     - include: tasks/create_rds.yml
               #tasks/getfroms3.yml