apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: samsara
spec:
  ports:
    - port: 5432
  selector:
    app: samsara
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgresdb
  labels:
    app: samsara
spec:
  selector:
    matchLabels:
      app: samsara
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samsara
    spec:
      containers:
      - image: 455022533484.dkr.ecr.us-east-1.amazonaws.com/postgresdb:latest
        name: postgresdb
        ports:
        - containerPort: 5432
          name: postgresdbdb