apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    service: postgresdb
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 32001
    targetPort: 5432
  selector:
    service: postgresdb
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    service: postgresdb
  name: postgresdb-deployment
spec:
  selector:
    matchLabels:
      service: postgresdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: postgresdb
    spec:
      containers:
      - image: 455022533484.dkr.ecr.us-east-1.amazonaws.com/postgresdb:latest
        name: postgresdb
        ports:
        - containerPort: 5432
          name: postgresdb-port
          protocol: TCP