apiVersion: v1
kind: Service
metadata:
  name: samsara
  labels:
    service: samsara
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    service: samsara
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    service: samsara
  name: samsara-deployment
spec:
  selector:
    matchLabels:
      service: samsara
  template:
    metadata:
      labels:
        service: samsara
    spec:
      containers:
      - image: 455022533484.dkr.ecr.us-east-1.amazonaws.com/samsara:latest
        name: samsara
        env:
        - name: DB_HOST
          value: "postgresdb.default.svc.cluster.local"
        - name: DB_NAME
          value: auradb
        - name: DB_USER
          value: aura
        - name: DB_PASS
          value: mysecretpassword
        ports:
        - containerPort: 9000
          protocol: TCP
          name: samsara-port